### ISSUE TITLE
스크린 리더로 19. Real Time Feedback in Web Forms 예제 중 ARIA 적용 사례 운용 시 undefined 오류 발생

### ISSUE THREAD

**Issue by dnz3d4c** [niawa/ARIA#1]
STR
1. Real Time Feedback in Web Forms 예제의 <Live Demo> 페이지 접속
2. ARIA 적용 사례 섹션으로 이동한 다음 탭 키를 사용하여 비밀번호 항목으로 이동
3. 숫자/문자 관계 없이 비밀번호 값을 입력함.

Expected Results:
1. 비밀번호 첫 번째 필드를 4글자 이하로 입력 시 undefined 결과가 발생함. 스크린 리더 음성 출력 결과도 동일함.

Actual Results:
1. 적절한 메시지(강도 취약등)가 출력되고, 스크린 리더 또한 동일한 결과를 전달받을 수 있어야 함.

Test Software:
- Screen Reader: NVDA 2016.3
- Browser: CR(57.0.2946.0), FF(50.0.2)

감사합니다.

**Comment by mulder21c** [comment]
@dnz3d4c JS 상에 오류가 있었네요 ^^; 수정을 했다고 생각을 했는데 작업 과정에서 해당 오류 수정이 누락되었던 듯 합니다. 알려주셔서 감사합니다 ^^
